# Generated by Django 2.0.7 on 2020-09-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfourthapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='myproduct',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
