# Generated by Django 2.0.7 on 2020-09-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfourthapp', '0003_auto_20200906_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproduct',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
